CI_VERSION: 2.0.196
TEAM_CHANNEL: core_ci
PROJECT: cob-loader-service
TERRAFORM_PROJECT: cob_loader_service
CONTAINER_IMAGE: cob-loader-service
SERVICE_NAME: datadog_service_multiple
BUILD_TYPE: JAVA
SKIP_TEST: false
LOGLEVEL: ERROR
DEPLOY: terraform_deploy
DEPLOY_DEV: terraform_deploy
DEPLOY_QA: terraform_deploy
DEPLOY_STAGE: terraform_deploy
DEPLOY_TRAIN: terraform_deploy
DEPLOY_PREP: terraform_deploy
DEPLOY_PROD: terraform_deploy
MAVEN_BUILD_VERSION_DEV: 1.0.1
MAVEN_BUILD_VERSION_QA: 1.0.1
MAVEN_BUILD_VERSION_STAGE: 1.0.1
MAVEN_BUILD_VERSION_MASTER: 1.0.1
BUILD_CONTAINER_DEV: concourseci-build-java
BUILD_CONTAINER_QA: concourseci-build-java
BUILD_CONTAINER_STAGE: concourseci-build-java
BUILD_CONTAINER_MASTER: concourseci-build-java
