CI_VERSION: 2.0.196
TEAM_CHANNEL: correspondence-dev
PROJECT: correspondence.he.proxy.svc
TERRAFORM_PROJECT: correspondence_he_proxy_svc
CONTAINER_IMAGE: correspondence-he-proxy-svc
SERVICE_NAME: ecs_service
BUILD_TYPE: JAVA
SKIP_TEST: false
LOGLEVEL: ERROR
DEPLOY: terraform_ecs_deploy
DEPLOY_DEV: terraform_ecs_deploy
DEPLOY_QA: terraform_ecs_deploy
DEPLOY_STAGE: terraform_ecs_deploy
DEPLOY_TRAIN: terraform_ecs_deploy
DEPLOY_PREP: terraform_ecs_deploy
DEPLOY_PROD: terraform_ecs_deploy
MAVEN_BUILD_VERSION_DEV: 1.0.0
MAVEN_BUILD_VERSION_QA: 1.0.0
MAVEN_BUILD_VERSION_STAGE: 1.0.0
MAVEN_BUILD_VERSION_MASTER: 1.0.0
BUILD_CONTAINER_DEV: concourseci-build-java17
BUILD_CONTAINER_QA: concourseci-build-java17
BUILD_CONTAINER_STAGE: concourseci-build-java17
BUILD_CONTAINER_MASTER: concourseci-build-java17
