TEAM_CHANNEL: api-gateway
CI_VERSION : 2.0.209
PROJECT: admin.portal
TERRAFORM_PROJECT: admin_portal
CONTAINER_IMAGE: admin-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: admin.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node