CI_VERSION : 2.0.151
TEAM_CHANNEL: devops-cicd
PROJECT: devops.infra.portals_ingress
CONTAINER_IMAGE: nomad-portals-ingress
SERVICE_NAME: nomad_service
BUILD_TYPE: NOMAD_SERVICE
SKIP_TEST: true
LOGLEVEL: ERROR
CONTAINER_TAGS: nomad
