TEAM_CHANNEL: devops-cicd
CI_VERSION : 2.0.209
PROJECT: devops.nginx.gump
TERRAFORM_PROJECT: nginx_gump
CONTAINER_IMAGE: nginx-gump
SERVICE_NAME: he_proxy_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NGINX
VERRACODE_APP: NA
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_ecs_deploy
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node