CI_VERSION: 2.0.196
TEAM_CHANNEL: practitioner
PROJECT: edi.generate837dental.svc
TERRAFORM_PROJECT: edi_generate837dental_service
CONTAINER_IMAGE: edi-generate837dental-service
SERVICE_NAME: datadog_service
BUILD_TYPE: JAVA
SKIP_TEST: false
LOGLEVEL: ERROR
DEPLOY: terraform_deploy
DEPLOY_DEV: terraform_deploy
DEPLOY_QA: terraform_deploy
DEPLOY_STAGE: terraform_deploy
DEPLOY_TRAIN: terraform_deploy
DEPLOY_PREP: terraform_deploy
DEPLOY_PROD: terraform_deploy
MAVEN_BUILD_VERSION_DEV: 1.0.0
MAVEN_BUILD_VERSION_QA: 1.0.0
MAVEN_BUILD_VERSION_STAGE: 1.0.0
MAVEN_BUILD_VERSION_MASTER: 1.0.0
BUILD_CONTAINER_DEV: concourseci-build-java17
BUILD_CONTAINER_QA: concourseci-build-java17
BUILD_CONTAINER_STAGE: concourseci-build-java17
BUILD_CONTAINER_MASTER: concourseci-build-java17
