CI_VERSION : 2.0.151
TEAM_CHANNEL: devops-cicd
PROJECT: devops.infra.tenant_cognito
CONTAINER_IMAGE: nomad-tenant-cognito
SERVICE_NAME: nomad_service
BUILD_TYPE: NOMAD_SERVICE
SKIP_TEST: true
LOGLEVEL: ERROR
CONTAINER_TAGS: nomad
