CI_VERSION : 2.0.151
TEAM_CHANNEL: practitioner
PROJECT: practitioner.s3toftpddpa.nomad
CONTAINER_IMAGE: practitioner-s3toftpddpa-nomad
SERVICE_NAME: nomad_service
BUILD_TYPE: NOMAD_SERVICE
CONTAINER_TAGS: nomad
