TEAM_CHANNEL: ice_ci
CI_VERSION : 2.0.209
PROJECT: benefit_explanation.portal
TERRAFORM_PROJECT: benefit_explanation_portal
CONTAINER_IMAGE: benefit_explanation-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: benefit_explanation.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node