CI_VERSION: 2.0.196
TEAM_CHANNEL: core_ci
PROJECT: odl-member-consumer-mongo-sink
TERRAFORM_PROJECT: odl-member-consumer-mongo-sink
CONTAINER_IMAGE: odl-member-consumer-mongo-sink
SERVICE_NAME: ecs_service
BUILD_TYPE: JAVA
SKIP_TEST: false
LOGLEVEL: ERROR
DEPLOY: terraform_ecs_deploy
DEPLOY_DEV: terraform_ecs_deploy
DEPLOY_QA: terraform_ecs_deploy
DEPLOY_STAGE: terraform_ecs_deploy
DEPLOY_TRAIN: terraform_ecs_deploy
DEPLOY_PREP: terraform_ecs_deploy
DEPLOY_PROD: terraform_ecs_deploy
MAVEN_BUILD_VERSION_DEV: 1.0.2
MAVEN_BUILD_VERSION_QA: 1.0.2
MAVEN_BUILD_VERSION_STAGE: 1.0.2
MAVEN_BUILD_VERSION_MASTER: 1.0.2
BUILD_CONTAINER_DEV: concourseci-build-java11
BUILD_CONTAINER_QA: concourseci-build-java11
BUILD_CONTAINER_STAGE: concourseci-build-java11
BUILD_CONTAINER_MASTER: concourseci-build-java11
