CI_VERSION : 2.0.104
PROJECT: finance.admin.db
BUILD_TYPE: POSTGRES
LOGLEVEL: ERROR
TEAM_CHANNEL: finance360
LIQUIBASE_PORT: 5432
LIQUIBASE_DATABASE: finance_admin
LIQUIBASE_USERNAME: corvesta
LIQUIBASE_CHANGELOG: changelog.xml
LIQUIBASE_LOGLEVEL: debug
LIQUIBASE_CLASSPATH: /opt/jdbc/postgres-jdbc.jar
LIQUIBASE_DRIVER: org.postgresql.Driver
LIQUIBASE_DEBUG: unset
