PROJECT: devops.certificate-renewal
CI_VERSION : 2.0.185
TERRAFORM_PROJECT: certificate-renewal 
TEAM_CHANNEL: devops-cicd
BUILD_TYPE: PYTHON
DEPLOY: lambda_terraform_deploy_2021
CI_IMAGE: concourseci-build-python-al2
CI_IMAGE_TAG: 1.0.0
PIP_PATH: ""
