TEAM_CHANNEL: devops-cicd
CI_VERSION : 2.0.209
PROJECT: devops.nginx.load-balancer
TERRAFORM_PROJECT: nginx_load_balancer
CONTAINER_IMAGE: load-balancer
SERVICE_NAME: ecs_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NGINX
VERRACODE_APP: NA
VALIDATE_NGINX_CONFIGS: true
DEPLOY: terraform_ecs_deploy
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node
