CI_VERSION : FOUND-18386
PROJECT: core.code_lists.db
BUILD_TYPE: POSTGRES
LOGLEVEL: ERROR
TEAM_CHANNEL: data
LIQUIBASE_PORT: 5432
LIQUIBASE_DATABASE: code_lists
LIQUIBASE_USERNAME: corvesta
LIQUIBASE_CHANGELOG: changelog.xml
LIQUIBASE_LOGLEVEL: debug
LIQUIBASE_CLASSPATH: /opt/jdbc/postgres-jdbc.jar
LIQUIBASE_DRIVER: org.postgresql.Driver
LIQUIBASE_DEBUG: unset
