TEAM_CHANNEL: portals_ci
CI_VERSION : 2.0.214
PROJECT: broker.portal
TERRAFORM_PROJECT: broker_portal
CONTAINER_IMAGE: broker-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: broker.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node_alb
DEPLOY_QA: terraform_deploy_node_alb
DEPLOY_STAGE: terraform_deploy_node_alb
DEPLOY_TRAIN: terraform_deploy_node_alb
DEPLOY_PREP: terraform_deploy_node_alb
DEPLOY_PROD: terraform_deploy_node_alb