TEAM_CHANNEL: portals_ci
CI_VERSION : 2.0.209
PROJECT: keyspring-storefront-portal
TERRAFORM_PROJECT: keyspring-storefront-portal
CONTAINER_IMAGE: keyspring-storefront-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: keyspring-storefront-portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node_alb
DEPLOY_DEV: terraform_deploy_node_alb
DEPLOY_QA: terraform_deploy_node_alb
DEPLOY_STAGE: terraform_deploy_node_alb
DEPLOY_TRAIN: terraform_deploy_node_alb
DEPLOY_PREP: terraform_deploy_node_alb
DEPLOY_PROD: terraform_deploy_node_alb
