TEAM_CHANNEL: core_ci
CI_VERSION : 2.0.104
PROJECT: helloworld.job
CONTAINER_IMAGE: helloworld-job
SERVICE_NAME: default_service
BUILD_TYPE: JAVA
MAVEN_BUILD_VERSION: 1.0.1
SKIP_TEST: false
LOGLEVEL: ERROR
CONTAINER_TAGS: nomad
