CI_VERSION: 2.0.181
TEAM_CHANNEL: billingnfinance
PROJECT: accounting.general_ledger.svc
TERRAFORM_PROJECT: accounting_gl_service
CONTAINER_IMAGE: accounting-gl-service
TERRAFORM_VERSION: 0.11.1
SERVICE_NAME: default_service
BUILD_TYPE: JAVA
MAVEN_BUILD_VERSION: 1.0.1
SKIP_TEST: true
LOGLEVEL: ERROR
