CI_VERSION : 2.0.207
TEAM_CHANNEL: helloworld
PROJECT: helloworld.ice
TERRAFORM_PROJECT: helloworld_ice
CONTAINER_IMAGE: helloworld-ice
TERRAFORM_VERSION: 0.11.1
SERVICE_NAME: talend_service
BUILD_TYPE: TALEND
MAVEN_BUILD_VERSION: 1.0.1
SKIP_TEST: true
LOGLEVEL: ERROR
FILTER: helloworld
MASTER_REPO: icegateway
CONTAINER_TAGS: nomad
DEPLOY_DEV:   deploy_nomad_jobs
DEPLOY_QA:    deploy_nomad_jobs
DEPLOY_STAGE: deploy_nomad_jobs
DEPLOY_TRAIN: deploy_nomad_jobs
DEPLOY_PREP:  deploy_nomad_jobs
DEPLOY_PROD:  deploy_nomad_jobs
