PROJECT: devops.lambda.failed-he-claims-attach
CI_VERSION : FOUND-9225
TERRAFORM_PROJECT: failed-he-claims-attach
TEAM_CHANNEL: devops-cicd
BUILD_TYPE: PYTHON
DEPLOY: lambda_terraform_deploy_2021
CI_IMAGE: concourseci-alpine-p3-tf
CI_IMAGE_TAG: 1.0.0
PIP_PATH: ""
