CI_VERSION : 2.0.151
TEAM_CHANNEL: devops-cicd
PROJECT: devops.infra.hedns
CONTAINER_IMAGE: nomad-client-hedns
SERVICE_NAME: nomad_service
BUILD_TYPE: NOMAD_SERVICE
SKIP_TEST: true
LOGLEVEL: ERROR
CONTAINER_TAGS: nomad
