TEAM_CHANNEL: bs3_ci_cd
CI_VERSION : 2.0.209
PROJECT: benefit_services.portal
TERRAFORM_PROJECT: benefit_portal
CONTAINER_IMAGE: benefit-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: benefit_services.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node_alb
DEPLOY_DEV: terraform_deploy_node_alb
DEPLOY_QA: terraform_deploy_node_alb
DEPLOY_STAGE: terraform_deploy_node_alb
DEPLOY_TRAIN: terraform_deploy_node_alb
DEPLOY_PREP: terraform_deploy_node_alb
DEPLOY_PROD: terraform_deploy_node_alb