CI_VERSION : 2.0.104
PROJECT: core.activity-log.client.lib
BUILD_TYPE: JAVA_LIB
LOGLEVEL: INFO
TEAM_CHANNEL: core_ci
SKIP_TEST: true
MAVEN_BUILD_VERSION: 1.0.1
BUILD_CONTAINER: concourseci-build-java
