CI_VERSION : 2.0.207
TEAM_CHANNEL: ice_ci
PROJECT: ice.ci.generate834outbound
TERRAFORM_PROJECT: ice_generate_834_outbound
CONTAINER_IMAGE: ice-generate-834-outbound
SERVICE_NAME: talend_service
BUILD_TYPE: TALEND
MAVEN_BUILD_VERSION: 1.0.1
SKIP_TEST: true
LOGLEVEL: ERROR
FILTER: generate834OutboundVision
MASTER_REPO: icegateway
CONTAINER_TAGS: nomad
DEPLOY_DEV:   deploy_nomad_jobs
DEPLOY_QA:    deploy_nomad_jobs
DEPLOY_STAGE: deploy_nomad_jobs
DEPLOY_TRAIN: deploy_nomad_jobs
DEPLOY_PREP:  deploy_nomad_jobs
DEPLOY_PROD:  deploy_nomad_jobs
