TEAM_CHANNEL: devops-cicd
CI_VERSION : 2.0.209
PROJECT: devops.nginx.emma
TERRAFORM_PROJECT: nginx_emma
CONTAINER_IMAGE: nginx-emma
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NGINX
VERRACODE_APP: NA
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node
