TEAM_CHANNEL: claim360deploy
CI_VERSION : 2.0.209
PROJECT: claim360.portal
TERRAFORM_PROJECT: claim360_portal
CONTAINER_IMAGE: claim360-portal
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: claim360.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node_alb
DEPLOY_QA: terraform_deploy_node_alb
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node