---

shared:
  - &failure-alert
    put: slack-alert
    params:
      channel: ((TEAM_CHANNEL))
      always_notify: true
      username: "Concource CI"
      silent: true
      icon_emoji: ":interrobang:"
      text: |
        *The <http://concoursecinew.mgmt.corvesta.net/teams/developer/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job failed!*
    get_params: { skip_download: true }

  - &success-alert
    put: slack-alert
    params:
      channel: ((TEAM_CHANNEL))
      always_notify: true
      username: "Concource CI"
      silent: true
      icon_emoji: ":rocket:"
      text: |
        *The <http://concoursecinew.mgmt.corvesta.net/teams/developer/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job passed!*
    get_params: { skip_download: true }

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: 038131160342.dkr.ecr.us-east-1.amazonaws.com/slack-notification-resource
    tag: latest
    aws_secret_access_key: ((MGMT_AWS_SECRET_ACCESS_KEY))
    aws_access_key_id: ((MGMT_AWS_ACCESS_KEY_ID))


resources:

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_channel))

- name: resource-devops.ci
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/devops.ci.git
    branch: ((CI_VERSION))
    private_key: ((bitbucket-ssh))

- name: dev
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: develop
    private_key: ((bitbucket-ssh))

- name: qa
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: qa
    private_key: ((bitbucket-ssh))

- name: stage
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: stage
    private_key: ((bitbucket-ssh))

- name: train
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: train
    private_key: ((bitbucket-ssh))

- name: prep
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: prep
    private_key: ((bitbucket-ssh))

- name: master
  type: git
  check_timeout: 5m
  source:
    uri: git@bitbucket.org:corvesta/((PROJECT)).git
    branch: master
    private_key: ((bitbucket-ssh))

- name: terraform_deploy
  type: docker-image
  check_timeout: 5m
  source:
    repository: 038131160342.dkr.ecr.us-east-1.amazonaws.com/concourseci-deploy
    tag: 0.13.3
    aws_secret_access_key: ((MGMT_AWS_SECRET_ACCESS_KEY))
    aws_access_key_id: ((MGMT_AWS_ACCESS_KEY_ID))

groups:
- name: development
  jobs:
  - upload_((PROJECT))_to_dev

- name: test
  jobs:
  - upload_((PROJECT))_to_qa

- name: stage
  jobs:
  - upload_((PROJECT))_to_stage
  - upload_((PROJECT))_to_train

- name: production
  jobs:
  - upload_((PROJECT))_to_preprod
  - upload_((PROJECT))_to_prod


jobs:

- name: upload_((PROJECT))_to_dev
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: dev
        trigger: true
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: dev
      params: &dev_params
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((DEV_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((DEV_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: development
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva
    - task: upload-tenant_keys-from-git-ddco
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: dev
      params:
        <<: *dev_params
        TENANT: ddco
        CLIENT: ddco

- name: upload_((PROJECT))_to_qa
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: qa
        trigger: true
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: qa
      params: &qa_params
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((QA_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((QA_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: qa
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva
    - task: upload-tenant_keys-from-git-ddco
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: qa
      params:
        <<: *qa_params
        TENANT: ddco
        CLIENT: ddco

- name: upload_((PROJECT))_to_stage
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: stage
        trigger: true
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: stage
      params: &stage_params
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((STAGE_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((STAGE_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: staging
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva
    - task: upload-tenant_keys-from-git-ddco
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: stage
      params:
        <<: *stage_params
        TENANT: ddco
        CLIENT: ddco
    - task: upload-tenant_keys-from-git-ddks
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: stage
      params:
        <<: *stage_params
        TENANT: ddks
        CLIENT: ddks
    - task: upload-tenant_keys-from-git-taic
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: stage
      params:
        <<: *stage_params
        TENANT: taic
        CLIENT: taic

- name: upload_((PROJECT))_to_train
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: train
        trigger: true
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: train
      params:
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((TRAIN_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((TRAIN_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: training
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva

- name: upload_((PROJECT))_to_preprod
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: prep
        trigger: true
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: prep
      params: &prep_params
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((PREP_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((PREP_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: preprod
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva
    - task: upload-tenant_keys-from-git-ddco
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: prep
      params:
        <<: *prep_params
        TENANT: ddco
        CLIENT: ddco
    - task: upload-tenant_keys-from-git-ddks
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: prep
      params:
        <<: *prep_params
        TENANT: ddks
        CLIENT: ddks
    - task: upload-tenant_keys-from-git-taic
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: prep
      params:
        <<: *prep_params
        TENANT: taic
        CLIENT: taic

- name: upload_((PROJECT))_to_prod
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: master
    - task: upload-tenant_keys-from-git-ddva
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: master
      params: &prod_params
        STEP: APPLY
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_ACCESS_KEY_ID: ((PROD_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((PROD_AWS_SECRET_ACCESS_KEY))
        TERRAFORM_ENV: prod
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        TENANT: ddva
        CLIENT: ddva
    - task: upload-tenant_keys-from-git-ddco
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: master
      params:
        <<: *prod_params
        TENANT: ddco
        CLIENT: ddco
    - task: upload-tenant_keys-from-git-taic
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/terraform_consul.yml
      input_mapping:
        CODE: master
      params:
        <<: *prod_params
        TENANT: taic
        CLIENT: taic
