TEAM_CHANNEL: devops-cicd
CI_VERSION : 2.0.209
PROJECT: helloworld.portal
TERRAFORM_PROJECT: hello_world_portal
CONTAINER_IMAGE: hello-world-portal
SERVICE_NAME: ecs_service
SKIP_TEST: true
BUILD_TYPE: NODE
LOGLEVEL: ERROR
VERRACODE_APP: helloworld.portal
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_tfvars
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node