CI_VERSION: 2.0.197
PROJECT: sql_db_code_deploy.pricing_rating_engine.ddks
BUILD_TYPE: POSTGRES
LOGLEVEL: ERROR
TEAM_CHANNEL: data
CLIENT: ddks
LIQUIBASE_PORT: 5432
LIQUIBASE_DATABASE: pricing_rating_engine
LIQUIBASE_USERNAME: corvesta
LIQUIBASE_CHANGELOG: changelog.xml
LIQUIBASE_LOGLEVEL: debug
LIQUIBASE_CLASSPATH: /opt/jdbc/postgres-jdbc.jar
LIQUIBASE_DRIVER: org.postgresql.Driver
LIQUIBASE_DEBUG: unset
