TEAM_CHANNEL: api-gateway
CI_VERSION : 2.0.209
PROJECT: document-reader
TERRAFORM_PROJECT: document_reader
CONTAINER_IMAGE: document-reader
SERVICE_NAME: node_service
SKIP_TEST: true
LOGLEVEL: ERROR
BUILD_TYPE: NODE
VERRACODE_APP: document-reader
VALIDATE_NGINX_CONFIGS: false
DEPLOY: terraform_deploy_node
DEPLOY_DEV: terraform_deploy_node
DEPLOY_QA: terraform_deploy_node
DEPLOY_STAGE: terraform_deploy_node
DEPLOY_TRAIN: terraform_deploy_node
DEPLOY_PREP: terraform_deploy_node
DEPLOY_PROD: terraform_deploy_node