PROJECT: devops.env_mismatch_scanner
CI_VERSION : 2.0.181
TERRAFORM_PROJECT: env_mismatch_scanner
TEAM_CHANNEL: devops-cicd
BUILD_TYPE: PYTHON
DEPLOY: lambda_terraform_deploy_2021
CI_IMAGE: concourseci-alpine-p3-tf
CI_IMAGE_TAG: 1.0.0
PIP_PATH: ""
