PROJECT: devops.lambda.leased_networks
CI_VERSION : 2.0.155
TERRAFORM_PROJECT: leased_networks
TEAM_CHANNEL: devops-cicd
BUILD_TYPE: PYTHON
DEPLOY: lambda_terraform_deploy_2021
CI_IMAGE: concourseci-alpine-p3-tf
CI_IMAGE_TAG: 1.0.0
PIP_PATH: ""
