---

shared:
  - &failure-alert
    put: slack-alert
    params:
      channel: ((TEAM_CHANNEL))
      always_notify: true
      username: "Concource CI"
      silent: true
      icon_emoji: ":interrobang:"
      text: |
        *The <http://concoursecinew.mgmt.corvesta.net/teams/developer/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job failed!*

  - &success-alert
    put: slack-alert
    params:
      channel: ((TEAM_CHANNEL))
      always_notify: true
      username: "Concource CI"
      silent: true
      icon_emoji: ":rocket:"
      text: |
        *The <http://concoursecinew.mgmt.corvesta.net/teams/developer/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job passed!*

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: 038131160342.dkr.ecr.us-east-1.amazonaws.com/slack-notification-resource
    tag: latest
    aws_secret_access_key: ((MGMT_AWS_SECRET_ACCESS_KEY))
    aws_access_key_id: ((MGMT_AWS_ACCESS_KEY_ID))

- name: git-bitbucket-pr
  type: docker-image
  source:
    repository: zarplata/concourse-git-bitbucket-pr-resource

resources:

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_channel))

- name: resource-devops.ci
  type: git
  check_every: 5m
  check_timeout: 5m
  source:
    uri:  https://bitbucket.org/corvesta/devops.ci.git
    branch: ((CI_VERSION))
    username: ((bitbucket-username))
    password: ((bitbucket-apppassword))

- name: dev
  type: git
  check_timeout: 5m
  source: &branch_source
    uri: https://bitbucket.org/corvesta/((PROJECT)).git
    branch: develop
    username: ((bitbucket-username))
    password: ((bitbucket-apppassword))

- name: qa
  type: git
  check_timeout: 5m
  source:
    <<: *branch_source
    branch: qa

- name: stage
  type: git
  check_timeout: 5m
  source:
    <<: *branch_source
    branch: stage

- name: master
  type: git
  check_timeout: 5m
  source:
    <<: *branch_source
    branch: master

- name: terraform_deploy
  type: docker-image
  check_timeout: 5m
  check_every: 5h
  source:
    repository: 038131160342.dkr.ecr.us-east-1.amazonaws.com/((CI_IMAGE))
    tag: ((CI_IMAGE_TAG))
    aws_secret_access_key: ((MGMT_AWS_SECRET_ACCESS_KEY))
    aws_access_key_id: ((MGMT_AWS_ACCESS_KEY_ID))

groups:
- name: development
  jobs:
  - deploy_((PROJECT))_lambda_job_to_dev

- name: qa
  jobs:
  - promote_((PROJECT))_and_deploy_to_qa

- name: stage
  jobs:
  - promote_((PROJECT))_and_deploy_to_stage
  - promote_((PROJECT))_and_deploy_to_train

- name: production
  jobs:
  - promote_((PROJECT))_preprod_and_deploy
  - promote_((PROJECT))_and_deploy_to_production

jobs:
- name: deploy_((PROJECT))_lambda_job_to_dev
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: dev
        trigger: true
      - get: resource-devops.ci
      - get: terraform_deploy
    - task: terraform-deploy
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: dev}
      params: &deploy_params
        TERRAFORM_ENV: development
        TERRAFORM_PROJECT: ((TERRAFORM_PROJECT))
        TERRAFORM_TEAM_TOKEN: ((TERRAFORM_TEAM_TOKEN))
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((DEV_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((DEV_AWS_ACCESS_KEY_ID))
        GIT_USERNAME: ((bitbucket-username))
        GIT_PASSWORD: ((bitbucket-apppassword))
        ARTIFACTORYPASSWORD: ((ARTIFACTORYPASSWORD))
        BUILD_TYPE: ((BUILD_TYPE))
        PIP_PATH: ((PIP_PATH))

- name: promote_((PROJECT))_and_deploy_to_qa
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: qa
        trigger: true
      - get: resource-devops.ci
      - get: terraform_deploy
    - task: terraform-deploy
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: qa}
      params:
        <<: *deploy_params
        TERRAFORM_ENV: qa
        ENV_AWS_SECRET_ACCESS_KEY: ((QA_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((QA_AWS_ACCESS_KEY_ID))        


- name: promote_((PROJECT))_and_deploy_to_stage
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: stage
        trigger: true
      - get: resource-devops.ci
      - get: terraform_deploy
    - task: terraform-deploy
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: stage}
      params:
        <<: *deploy_params
        TERRAFORM_ENV: staging
        ENV_AWS_SECRET_ACCESS_KEY: ((STAGE_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((STAGE_AWS_ACCESS_KEY_ID))        

- name: promote_((PROJECT))_and_deploy_to_train
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: stage
        trigger: true
        passed: [promote_((PROJECT))_and_deploy_to_stage]
      - get: resource-devops.ci
      - get: terraform_deploy
    - task: terraform-deploy
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: stage}
      params:
        <<: *deploy_params
        TERRAFORM_ENV: training
        ENV_AWS_SECRET_ACCESS_KEY: ((TRAIN_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((TRAIN_AWS_ACCESS_KEY_ID))        

- name: promote_((PROJECT))_preprod_and_deploy
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: resource-devops.ci
      - get: terraform_deploy
      - get: master
        trigger: true
    - task: deploy-container-to-preprod
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: master}
      params:
        <<: *deploy_params
        TERRAFORM_ENV: preprod
        ENV_AWS_SECRET_ACCESS_KEY: ((PREP_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((PREP_AWS_ACCESS_KEY_ID))        

- name: promote_((PROJECT))_and_deploy_to_production
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - in_parallel:
      - get: master
        passed: [promote_((PROJECT))_preprod_and_deploy]
      - get: resource-devops.ci
      - get: terraform_deploy
    - task: terraform-deploy
      privileged: true
      image: terraform_deploy
      file: resource-devops.ci/tasks/((DEPLOY)).yml
      input_mapping: {CODE: master}
      params:
        <<: *deploy_params
        TERRAFORM_ENV: prod
        ENV_AWS_SECRET_ACCESS_KEY: ((PROD_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((PROD_AWS_ACCESS_KEY_ID))        
