CI_VERSION : 2.0.188
PROJECT: helloworld.sf.db
BUILD_TYPE: SNOWFLAKE
LOGLEVEL: ERROR
TEAM_CHANNEL: helloworld
LIQUIBASE_PORT: 443
LIQUIBASE_DATABASE: HELLOWORLD
LIQUIBASE_ROLE: SYSADMIN
LIQUIBASE_CHANGELOG: changelog.xml
LIQUIBASE_LOGLEVEL: debug
LIQUIBASE_DEBUG: unset
LIQUIBASE_SCHEMA: RAW