PROJECT: ice.lambda.cleanup
CI_VERSION : 2.0.161
TERRAFORM_PROJECT: ice_cleanup
TEAM_CHANNEL: devops-cicd
BUILD_TYPE: PYTHON
DEPLOY: lambda_terraform_deploy_2021
CI_IMAGE: concourseci-build-python-glibc
CI_IMAGE_TAG: 1.0.0
PIP_PATH: ""
